version: '3.8'

services:
  backend-laravel:
    build:
      context: ./backend-laravel 
      dockerfile: Dockerfile  
    container_name: backend-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend-laravel:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      - DB_DATABASE=docker_cloud_s5
      - DB_USERNAME=postgres
      - DB_PASSWORD=docker_cloud_s5

  backend-spring:
    image: openjdk:17-jdk-slim
    container_name: backend-spring
    volumes:
      - ./backend-spring:/spring-boot
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    working_dir: /spring-boot
    command: ["sh", "-c", "./mvnw spring-boot:run"]

  frontend-vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vuejs
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VUE_APP_BACKEND_URL=${VUE_APP_BACKEND_URL}
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pg_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: docker_cloud_s5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker_cloud_s5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data