version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project_cloud_s5
    container_name: project_cloud_s5
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_DATABASE=docker_cloud_s5
      - DB_USERNAME=postgres
      - DB_PASSWORD=docker_cloud_s5

  db:
    image: postgres:15
    container_name: pg_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: docker_cloud_s5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker_cloud_s5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
volumes:
  db_data: